channels:
    - conda-forge
    - pyviz
dependencies:
    - cartopy
    - proj4<6
    - geoviews
    - pip
    - pip:
      - -r file:./NetCDF_Manipulations/requirements.txt
      - -r file:./Analysis/requirements.txt
